search_results = {
    "Google Results for Samsung smartphone": [
        "https://www.samsung.com/us/smartphones/",
        "https://www.samsung.com/us/",
        "https://www.samsung.com/us/mobile/phones/all-phones/",
        "https://www.verizon.com/smartphones/samsung/",
        "https://www.samsung.com/levant/smartphones/all-smartphones/",
        "https://www.bestbuy.com/site/mobile-cell-phones/samsung-galaxy/pcmcat305200050001.c?id=pcmcat305200050001",
        "https://eu.community.samsung.com/t5/other-galaxy-s-series/samsung-smartphone-with-asha-technology/td-p/3038370",
        "https://www.reddit.com/r/SamsungDex/comments/ke63xo/moving_mouse_between_samsung_smartphone_and/",
        "https://www.amazon.com/samsung-smartphones/s?k=samsung+smartphones",
        "https://news.samsung.com/global/how-samsung-galaxy-has-rewritten-smartphone-history-in-10-innovative-technologies",
        "https://semiconductor.samsung.com/processor/showcase/smartphone/",
        "https://meta.stackoverflow.com/questions/401413/how-can-i-type-backticks-on-my-samsung-smartphone-which-are-needed-for-inline-c",
        "https://insights.samsung.com/2023/02/09/8-tips-for-maximizing-your-smartphones-battery-life-3/",
        "https://community.spiceworks.com/t/any-way-to-reset-unlock-a-terminated-employees-company-samsung-smartphone/778454",
        "https://answers.microsoft.com/en-us/msoffice/forum/all/why-do-screenshots-from-my-samsung-smartphone/02281d1f-f382-4fce-90a5-befc879bb785",
        "https://www.sciencedirect.com/science/article/pii/S1877042816300696",
        "https://en.wikipedia.org/wiki/Samsung_Galaxy",
        "https://www.quora.com/Which-came-first-the-Apple-smartphone-or-the-Samsung-smartphone",
        "https://www.t-mobile.com/offers/samsung-phone-deals",
        "https://www.googlenestcommunity.com/t5/Cameras-and-Doorbells/Nest-doorbell-and-cam-whit-Samsung-smartphone/td-p/94985"
    ],
    "Google Results for Motorola smartphone": [
        "https://www.motorola.com/us/smartphones",
        "https://www.reddit.com/r/motorola/comments/11yjtio/how_good_are_motorola_phones_really/",
        "https://www.motorola.com/us/",
        "https://www.reddit.com/r/Android/comments/19bcosq/lenovo_bets_its_motorola_smartphone_brand_will_be/",
        "https://www.zdnet.com/article/i-wore-motorolas-bendable-smartphone-watch-hybrid-and-it-left-me-all-kinds-of-confused/",
        "https://www.verizon.com/smartphones/motorola/",
        "https://www.wired.com/story/best-motorola-phones/",
        "https://forums.lenovo.com/t5/Moto-G5-Moto-G5-Plus/Moto-smartphones-with-removable-battery-in-2023/m-p/5245119",
        "https://mea.motorola.com/smartphones-moto-edge-40/p",
        "https://www.walmart.com/browse/cell-phones/motorola-phones/1105910_7551331_4278347",
        "https://www.motorola.co.uk/smartphones",
        "https://en.wikipedia.org/wiki/Motorola_Mobility",
        "https://www.washingtonpost.com/news/innovations/wp/2013/10/31/why-i-dumped-my-smartphone-for-a-7-year-old-motorola-razr/",
        "https://en-us.support.motorola.com/app/software-upgrade",
        "https://us.motorola.com/smartphones-moto-g-stylus-5g-gen-4/p",
        "https://en-emea.support.motorola.com/app/answers/detail/a_id/160550/~/smart-connect-compatibility-chart",
        "https://www.motorola.in/",
        "https://we.motorola.com/smartphones-moto-e-13/p",
        "https://www.lenovo.com/us/en/d/motorola-smartphones/",
        "https://news.lenovo.com/pressroom/press-releases/motorola-redefines-possible-ai-adaptive-display-tech-world-2023/"
    ],
    "Google Results for LG smartphone": [
        "https://www.lg.com/levant_en/smartphones",
        "https://www.reddit.com/r/LGV60/comments/169p8g2/lg_to_start_making_mobile_phones_again_if/",
        "https://www.lg.com/us/cell-phones",
        "https://www.reddit.com/r/LGV60/comments/xlnema/now_that_lg_isnt_making_smart_phones_anymore/",
        "https://www.lg.com/levant_en/mobile-phones",
        "https://www.reddit.com/r/Smartphones/comments/rucn3g/need_help_with_alternatives_to_the_awesomeness_of/",
        "https://www.forbes.com/sites/ianmorris/2014/07/11/lg-g3-review-the-perfect-smartphone/",
        "https://www.reddit.com/r/TIdaL/comments/jzgy7s/mqa_files_with_lg_mobile_phones/",
        "https://www.quora.com/Are-lg-phones-good",
        "https://www.reddit.com/r/LGV60/comments/12c8d2y/lg_is_still_selling_phones_in_korea_and_its_5g/",
        "https://www.gsmarena.com/lg-phones-20.php",
        "https://www.reddit.com/r/Android/comments/mlklc5/mkbhd_why_did_lg_phones_really_die/",
        "https://www.walmart.com/browse/cell-phones/lg-phones/1105910_7551331_3916202",
        "https://audiosciencereview.com/forum/index.php?threads/review-and-audio-measurement-of-lg-g7-thinq-smartphone.4468/",
        "https://www.etdphotography.com/blog/2015/7/10/lg-g4-smartphone-camera-review-dslr-replacement",
        "https://www.statista.com/chart/24569/global-smartphone-market-share/",
        "https://www.amazon.com/LG-Smartphone/s?k=LG+Smartphone",
        "https://community.hsn.com/forums/customer-service-help-support/lg-smartphone-tracfone-is-going-out-of-business/1080732/",
        "https://www.techradar.com/news/best-lg-phones",
        "https://www.androidpolice.com/lg-electronics-pivoting-to-global-entertainment/"
    ]
}
yahoo_search_results = {
    "Yahoo Results for Samsung smartphone": [
        "https://www.samsung.com/us/smartphones/",
        "https://images.search.yahoo.com/search/images?p=Samsung+smartphone",
        "https://www.samsung.com/us/mobile/phones/all-phones/",
        "https://www.samsung.com/us/mobile/",
        "https://www.bestbuy.com/site/mobile-cell-phones/samsung-galaxy/pcmcat305200050001.c?id=pcmcat305200050001",
        "https://www.bestbuy.com/site/samsung-galaxy/all-samsung-galaxy-phones/pcmcat1661803373461.c?id=pcmcat1661803373461",
        "https://www.samsung.com/us/smartphones/",
        "https://news.samsung.com/us/samsung-galaxy-s21-ultra-unpacked-2021-ultimate-smartphone-experience-designed-epic/",
        "https://www.amazon.com/Samsung-Galaxy-S21-5G-Snapdragon/dp/B092CFFM84"
    ],
    "Yahoo Results for Motorola smartphone": [
        "https://www.motorola.com/us/smartphones",
        "https://images.search.yahoo.com/search/images?p=Motorola+smartphone",
        "https://www.motorola.com/us/smartphones-moto-g-5g-gen-2/p?skuId=894",
        "https://news.search.yahoo.com/search?p=Motorola+smartphone&fr2=p%3As%2Cv%3Aw%2Cm%3Anewsdd_sna_t%2Cct%3Anuwa",
        "https://us.motorola.com/smartphones-2",
        "https://www.motorola.com/us/smartphones-moto-g-5g-gen-3/p",
        "https://us.motorola.com/",
        "https://wwwuat.motorola.com/us/smartphones",
        "https://www.androidcentral.com/best-motorola-phones"
    ],
    "Yahoo Results for LG smartphone": [
        "https://www.lg.com/us/android-phones",
        "https://www.lg.com/us/cell-phones",
        "https://www.lg.com/us/smartphones/view-all",
        "https://www.bestbuy.com/site/shop/lg-phones",
        "https://www.gsmarena.com/lg-phones-20.php",
        "https://www.techradar.com/news/best-lg-phones",
        "https://www.walmart.com/browse/cell-phones/lg-phones/1105910_7551331_3916202"
    ]
}
bing_search_results = {
    "Bing Results for Samsung smartphone": [
        "https://www.samsung.com/us/smartphones/",
        "https://www.samsung.com/us/mobile/phones/all-phones/",
        "https://www.samsung.com/us/mobile/",
        "https://www.bestbuy.com/site/samsung-galaxy/all-samsung-galaxy-phones/pcmcat1661803373461.c?id=pcmcat1661803373461",
        "https://www.cnet.com/tech/mobile/best-samsung-galaxy-phone/",
        "https://news.samsung.com/us/samsung-galaxy-s21-ultra-unpacked-2021-ultimate-smartphone-experience-designed-epic/",
        "https://www.amazon.com/Samsung-Galaxy-S21-5G-Snapdragon/dp/B092CFFM84"
    ],
    "Bing Results for Motorola smartphone": [
        "https://www.motorola.com/us/smartphones",
        "https://us.motorola.com/smartphones-2",
        "https://www.motorola.com/us/smartphones-moto-g-5g-gen-3/p",
        "https://wwwuat.motorola.com/us/smartphones",
        "https://us.motorola.com/",
        "https://www.techradar.com/news/best-moto-phones",
        "https://www.bestbuy.com/site/brands/motorola/pcmcat159400050006.c?id=pcmcat159400050006"
    ],
    "Bing Results for LG smartphone": [
        "https://www.lg.com/us/android-phones",
        "https://www.lg.com/us/cell-phones",
        "https://www.lg.com/us/smartphones/view-all",
        "https://www.bestbuy.com/site/shop/lg-phones",
        "https://www.techradar.com/news/best-lg-phones",
        "https://www.androidauthority.com/best-lg-phones-775532/",
        "https://www.gsmarena.com/lg-phones-20.php"
    ]
}
